### ISSUE TITLE
Nuget packages in custom observers

### ISSUE THREAD

**Issue by adamtickner** [microsoft/service-fabric-observer#139]
Is it possible to support the use of nuget packages in observer plugins?

**Comment by GitTorre** [comment]
Hi,

Thanks for the question/issue (it may be more of an issue than a question).

Do you mean installing nupkgs into a plugin project? Yes, however, since a plugin is just a dll which gets loaded into the FO process at runtime, you would need to make sure the dlls houesd in the nuget packages that your plugin requires are also shipped with FO (you could try putting them into the plugins folder or adding them to FO's code package):

- Ship nupkg libs with the plugin in the plugins folder (I am not sure this will always work, however).
- Or you ship FO from the plugin project output (see ContainerObserver) and ensure the package dlls are in place in the code FO code package.

The key here is that, as you can imagine, any external lib that nuget package's contain must be available to load into the FO process along with the plugin lib. I have not done a lot of testing with using nuget packages in a plugin that FO does not also ship with. This is certainly something that should be made to reliably work as it enables more capabilities for a plugin. 

I would imagine you are filing this issue because you can't get it to work with either of the above suggestions?

**Comment by GitTorre** [comment]
I just added Polly (retry/circuit breaker) nupkg to sample observer as a test on my local dev machine, copied Polly.dll into FO/config/data/plugins folder and it worked.

**Comment by GitTorre** [comment]
It is unclear to me what support FO can offer here on its own. You build your plugin with nuget package refs. You the copy the related dlls to FO's plugins folder. The loader should find them there. If not, then add them to FO's code package (Code folder).

**Comment by GitTorre** [comment]
See the [SampleNewObserver](https://github.com/microsoft/service-fabric-observer/tree/main/SampleObserverPlugin) project for an example of how to do this with post-build events.

**Comment by adamtickner** [comment]
Thanks. In response to your earlier question, I had no luck when loading the observer dynamically but I will follow your latest example and get back to you if this does not work.

**Comment by GitTorre** [comment]
Cool. Also let me know what nuget package is failing for you if the solution does not work. Then I can debug with it. 

All plugins are loaded dynamically from the Plugins folder, so I am unsure what you mean. The CLR loader will look for ref/dependencies in the same folder the plugin is loaded from by default. It should just work (assuming you also include any of the dependencies the ref'd package lib has, if any, and if they are not also used by FO since they would already be in the Code folder).

**Comment by adamtickner** [comment]
This solution worked for me, I must have been trying to load the dependencies from the wrong location before.

The only thing I had to do extra was add a Directory.Build.props file containing the following to my plugin repo to get it to build on the CI server.

`<Project>
 <PropertyGroup>
    <SolutionDir>$(MSBuildThisFileDirectory)</SolutionDir>
 </PropertyGroup>
</Project>`
