### ISSUE TITLE
Add ARM template for FO deployment (using Releases SFPKG)

### ISSUE THREAD

**Issue by GitTorre** [microsoft/service-fabric-observer#166]
Add an ARM template to the repo that can be used to deploy FO using the appropriate SFPKG located in Releases. Given that most of FO's setting are overridable Application Parameters, this would be helpful for quick and easy deployment. More work to do to make this possible, but we're close.

**Comment by inputoutputcode** [comment]
Unfortunately, the declaration of DefaultServices in the ApplicationManifest.xml file is not supported with using ARM application resources. 
Source: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-concept-resource-model#upgrade-the-service-fabric-application-by-using-resource-manager

Starting with the SDK version 5.0.516.9590, released with 8.0 CU1 in May 2020.  
Source: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-startupservices-model 

Same functionality as with DefaultServices is now called StartupServices and separated in XML files. In this way only deployments with Visual Studio automatically creating service instances. All other deployments do not have the risk of using DefaultServices as this is not the best practice for production deployments. Anyway, monitoring applications like FabricObserver should be created with infrastructure deployment at the same time. This guarantees to deliver high quality monitoring data from the very beginning.

I'm proposing to build the same binaries with the model, so that we can use it with the ARM template in the linked PR.

**Comment by GitTorre** [comment]
You can see progress in the 8x_ARM branch (currently behind develop..).

**Comment by GitTorre** [comment]
This is now in place in develop and net6 branches.
