### ISSUE TITLE
With support for .Net 3.1 ending tin 6 months, can it be migrated to .Net 6 (LTS)

### ISSUE THREAD

**Issue by Mahons** [microsoft/service-fabric-observer#214]
[.Net Core 3.1 (LTS)](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) goes end of life on the 13th of December 2022. 

To maintain support, can this project please be upgraded to .NET 6 (LTS)

**Comment by Mahons** [comment]
Thanks @GitTorre, apologies, I hadn't spotted the net6 branch. Any ETA on when it will be ready?

**Comment by GitTorre** [comment]
> Thanks @GitTorre, apologies, I hadn't spotted the net6 branch. Any ETA on when it will be ready?

No need to apologize and the branch was local until yesterday.. It's a great question! As to when it will ship, I'm hoping in the next few weeks as it will be part of the 3.2.x wave of releases (3.2.1, specifically) and there is more work to do in a few areas (unrelated to .net runtime versions). Do note that the net6.0 versions of FO and CO require SF runtime version 9.0 and higher.

**Comment by Mahons** [comment]
Thanks @GitTorre, that explains how I missed it when I looked at the branches! That's great that your aiming for the next few weeks. Thankfully, we're already in the process of upgrading our estate to 9.0.

**Comment by GitTorre** [comment]
> Thanks @GitTorre, that explains how I missed it when I looked at the branches! That's great that your aiming for the next few weeks. Thankfully, we're already in the process of upgrading our estate to 9.0.

I reserve the right to define what "a few" means :)

The plan is:

Release 3.2.0 which targets SF runtime 8.x and .netcoreapp3.1
Release 3.2.1 which targets SF runtime 9.x and .net6

Once 3.1 is obsolete, folks will need to move to .net6 and so that means SF runtime 9.x and FO 3.2.1+. 

3.2.0 will be the last version of FO that targets .net core 3.1. So, folks can stay on that until they upgrade to SF runtime 9.x.

Sounds like a good plan?

...Charles

**Comment by Mahons** [comment]
Hi Charles (@GitTorre),

That sounds like a reasonable plan to me. 

Looking forward to them arriving in a "few" weeks. 

Best,

Stephen
