### ISSUE TITLE
Check for Windows Updates being disabled should pass if Automatic Updates are set to “never check for updates”

### ISSUE THREAD

**Issue by markwragg** [microsoft/service-fabric-observer#64]
Per comments I added to #59: Currently the code does the following check for if Windows Updates are enabled (which is if the service is enabled then the setting must be "notify before download"):
```
   this.isWindowsUpdateAutoDownloadEnabled =
                    wuLibAutoUpdates.ServiceEnabled &&
                    wuLibAutoUpdates.Settings.NotificationLevel != AutomaticUpdatesNotificationLevel.aunlNotifyBeforeDownload;
```

In my environment, the service is enabled but Windows Update is set to "never check for updates". I think the above check should be amended to include that as an additional acceptable sign that Windows updates are disabled (the enum to check I believe would be `AutomaticUpdatesNotificationLevel.aunlDisabled`).

Note also that I set `virtualMachineProfile.osProfile.windowsConfiguration.enableAutomaticUpdates` to false in the ARM template as per the guide on VMSS automatic OS image upgrades and this still didn't end up putting Windows Update in a state where it was disabled for my environment (even for new nodes that were created after the change). Although its worth noting that we have a boot script that sets auto updates to "never check for updates" in the registry so maybe this has overridden the default setting that this ARM property sets (and that it would have been the one you currently check for). I was surprised the ARM setting didn't just disable the Windows Update service, but it seems it does not.

**Comment by GitTorre** [comment]
You don't want to disable Windows Update completely. That is not a secure thing to do. Please don't try that (you probably can't do that anyway). 

The OSObserver check is to make sure that automatic download of windows updates is disabled not a check to see if you have disabled AU. POA, for example, requires AU and will override settings that attempt to disable it. VMSS auto image upgrade does not need AU. 

The goal of the OSObserver check is to get customers to POA or VMSS automatic os image update _quickly_, as AU with with automatic download enabled can lead to instability in clusters due to potential concurrent VM reboots (unexpected). You really do need either POA or VMSS auto os image update service. 

Perhaps a better check for the purposes of OSObserver is:

 var wuLibAutoUpdates = new AutomaticUpdatesClass();
                this.isWindowsUpdateAutoDownloadEnabled =
                    wuLibAutoUpdates.ServiceEnabled &&
                    wuLibAutoUpdates.Settings.NotificationLevel == AutomaticUpdatesNotificationLevel.aunlScheduledInstallation;

**Comment by markwragg** [comment]
Thanks for the update. I agree the revised check seems sensible and will resolve my use case.

**Comment by GitTorre** [comment]
Thank you for bug report! 2.0.7 shipped.

**Comment by markwragg** [comment]
Just thought I’d let you know I’ve tested this and it’s working fine for me.
